version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:14.15.0
    steps:
      - checkout
      - run:
          name: Dependencies
          command: |
            npm install
      - run:
          name: Tests
          command: |
            npm test
      - store_artifacts:
          path: reports 
workflows:
  build_test:
    jobs:
      - run_tests                     
          